entityName: 'Grupo'
entity: 'MWSimple\Bundle\ForoBundle\Entity\Grupo'
repository: 'MWSimpleForoBundle:Grupo'
index: 'foro_grupo'
new: 'foro_grupo_new'
edit: 'foro_grupo_edit'
show: 'foro_grupo_show'
create: 'foro_grupo_create'
update: 'foro_grupo_update'
delete: 'foro_grupo_delete'
export: 'foro_grupo_export'
sessionFilter: 'GrupoControllerFilter'
saveAndAdd: true
fieldsindex:
    # a.id:
    #     label: 'Id'
    #     name: 'Id'
    #     type: 'integer'
    #     export: true
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
        export: true
fieldsshow:
    a.nombre:
        label: 'Nombre'
        name: 'Nombre'
        type: 'string'
        class: 'col-lg-8'
        closerow: true
    a.miembros:
        label: 'Miembros'
        name: 'Miembros'
        type: 'ONE_TO_MANY'
        #class: 'col-lg-12'
        #closerow: true